version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest-boilerplate-api
    env_file:
      - .env
      - .env.development
    ports:
      - "${DOCKER_PORT}:${PORT}"
    volumes:
      - ./:/home/node/app
    command: npm run start:dev
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./:/home/data
    container_name: nest-boilerplate-db-mongo
