# Check out https://hub.docker.com/_/node to select a new base image
FROM node:alpine

# Set to a non-root built-in user `node`
USER node

# Create app directory (with user `node`)
RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY package*.json ./

ARG PORT=3000

COPY . .

EXPOSE $PORT
