version: '2'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ${DOCKER_CONTAINER_NAME}
    env_file:
      - .env
      - .env.integration
    environment:
      NODE_ENV: "integration"
    ports:
      - "${DOCKER_PORT}:${PORT}"
    volumes:
      - ./:/home/node/app
    networks:
      - crm-network
    restart: always
    command: npm run start:dev
networks:
  crm-network:
    external:
      name: ${CRM_NETWORK}